### ISSUE TITLE
allow using custom .js filename when loading a Microfrontend application

### ISSUE THREAD

**Issue by capitanfindusfi** [CapitanFindusFI/react-microfrontend-container#1]
Update MicroApp type with a property indicating the `.js` filename to load, as well as the `useMicroapp` hook.

Also, README.md should be updated (the `MicroApp` type section)

**Comment by Trafitto** [comment]
I can do this :muscle:

**Comment by capitanfindusfi** [comment]
Closed [here](https://github.com/CapitanFindusFI/react-microfrontend-container/pull/4)
