### ISSUE TITLE
Allow custom fetch configuration

### ISSUE THREAD

**Issue by capitanfindusfi** [CapitanFindusFI/react-microfrontend-container#2]
Allow passing a custom fetch configuration when loading the application _"manifest"_. Inside `useAppManifest` hook, a custom fetch configuration should be allowed (still using the current one as default)

**Comment by Trafitto** [comment]
I also can do this

**Comment by capitanfindusfi** [comment]
[related PR](https://github.com/CapitanFindusFI/react-microfrontend-container/pull/3) already merged and closed
